version: '3.8'

services:
    server:
        env_file: environment.env
        image: thoughts_frontend
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        ports:
            - "8002:8000"
